// Author byline: a small progressive-enhancement module (like narrator.ts /
// comments.ts / the figures) that renders "who wrote this" — name, avatar, and
// social links — into the article header.
//
// Why client-side rather than baked into the served HTML at build time: posts
// are served as opaque static bundles in BOTH dev (Bun's HTMLBundle) and prod
// (Cloudflare's ASSETS binding), and the dev bundle can't be rewritten the way
// the prod `dist/` is (see createDevServer.ts). Rendering the byline on the
// client is the one path that behaves identically in dev and prod — the same
// reason every other in-page feature here is a client module. Crawler-facing
// author metadata (JSON-LD `author`, `og:`) is emitted into <head> at build
// time separately, so SEO doesn't depend on this running.
//
// The data comes from `/assets/authors.json` — a public map (post path →
// {name, links, avatar}) generated by the build (copy-static.ts) and served
// fresh in dev. It contains NO email: the avatar URL embeds the public handle,
// keeping the address out of the response exactly as the served-HTML strip
// intends. See shared/authorProfile.ts.

type PublicAuthorProfile = {
  name: string;
  links: Record<string, string>;
  avatar: string | null;
};

// Display label for a known link key; unknown keys fall back to the key itself.
const LINK_LABELS: Record<string, string> = {
  x: "X",
  twitter: "X",
  github: "GitHub",
  bluesky: "Bluesky",
  mastodon: "Mastodon",
  website: "Website",
  web: "Website",
};

function normalizePath(pathname: string): string {
  // Map paths consistently with the build's keys (`/posts/<slug>`): drop a
  // trailing slash, and never key on a bare `/`.
  if (pathname.length > 1 && pathname.endsWith("/")) return pathname.slice(0, -1);
  return pathname;
}

function buildByline(profile: PublicAuthorProfile): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "byline";
  wrap.setAttribute("role", "group");
  wrap.setAttribute("aria-label", "Author");

  if (profile.avatar) {
    const img = document.createElement("img");
    img.className = "byline-avatar";
    img.src = profile.avatar;
    img.width = 48;
    img.height = 48;
    img.alt = profile.name;
    img.loading = "lazy";
    img.decoding = "async";
    wrap.appendChild(img);
  }

  const text = document.createElement("div");
  text.className = "byline-text";

  const name = document.createElement("span");
  name.className = "byline-name";
  name.textContent = profile.name;
  text.appendChild(name);

  const linkKeys = Object.keys(profile.links);
  if (linkKeys.length > 0) {
    const links = document.createElement("span");
    links.className = "byline-links";
    for (const key of linkKeys) {
      const href = profile.links[key];
      if (!href) continue;
      const a = document.createElement("a");
      a.className = `byline-link byline-link-${key}`;
      a.href = href;
      a.target = "_blank";
      // `author`/`me` mark this as the author's own identity link; `noopener`
      // for the new tab.
      a.rel = "author me noopener";
      a.textContent = LINK_LABELS[key] ?? key;
      links.appendChild(a);
    }
    text.appendChild(links);
  }

  wrap.appendChild(text);
  return wrap;
}

async function boot(): Promise<void> {
  // Same article-root selector the comments layer uses; present on every post
  // (kept even on narration opt-out posts).
  const article = document.querySelector<HTMLElement>("[data-narration-src]");
  if (!article) return;
  // Idempotent — never render two bylines.
  if (article.querySelector(".byline")) return;

  let map: Record<string, PublicAuthorProfile>;
  try {
    const res = await fetch("/assets/authors.json", { credentials: "omit" });
    if (!res.ok) return;
    map = (await res.json()) as Record<string, PublicAuthorProfile>;
  } catch {
    return;
  }

  const profile = map[normalizePath(location.pathname)];
  if (!profile || !profile.name) return;

  const byline = buildByline(profile);
  // Place it directly under the lede if present, else under the <h1> title,
  // else at the top of the article.
  const lede = article.querySelector("#lede");
  const title = article.querySelector("#title");
  if (lede) lede.after(byline);
  else if (title) title.after(byline);
  else article.prepend(byline);
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", () => void boot());
} else {
  void boot();
}
