// Author byline: a small progressive-enhancement module (like narrator.ts /
// comments.ts / the figures) that renders "who wrote this" — name, avatar, and
// social links — into the article header.
//
// Why client-side rather than baked into the served HTML at build time: posts
// are served as opaque static bundles in BOTH dev (Bun's HTMLBundle) and prod
// (Cloudflare's ASSETS binding), and the dev bundle can't be rewritten the way
// the prod `dist/` is (see createDevServer.ts). Rendering the byline on the
// client is the one path that behaves identically in dev and prod — the same
// reason every other in-page feature here is a client module. Crawler-facing
// author metadata (JSON-LD `author`, `og:`) is emitted into <head> at build
// time separately, so SEO doesn't depend on this running.
//
// The data comes from `/assets/authors.json` — a public map (post path →
// {name, links, avatar}) generated by the build (copy-static.ts) and served
// fresh in dev. It contains NO email: the avatar URL embeds the public handle,
// keeping the address out of the response exactly as the served-HTML strip
// intends. See shared/authorProfile.ts.

// FontAwesome Free v7 brand/solid SVGs, imported as inline text so they end up
// in the JS bundle (no webfont, no extra <link>, nothing for CSP `font-src` to
// govern). Each SVG paints with `fill="currentColor"`, so the icon inherits
// the anchor's text color and hover state automatically. Unknown link keys
// fall back to a plain text label.
import faGithub from "@fortawesome/fontawesome-free/svgs/brands/github.svg" with { type: "text" };
import faXTwitter from "@fortawesome/fontawesome-free/svgs/brands/x-twitter.svg" with { type: "text" };
import faBluesky from "@fortawesome/fontawesome-free/svgs/brands/bluesky.svg" with { type: "text" };
import faMastodon from "@fortawesome/fontawesome-free/svgs/brands/mastodon.svg" with { type: "text" };
import faLinkedin from "@fortawesome/fontawesome-free/svgs/brands/linkedin.svg" with { type: "text" };
import faYoutube from "@fortawesome/fontawesome-free/svgs/brands/youtube.svg" with { type: "text" };
import faThreads from "@fortawesome/fontawesome-free/svgs/brands/threads.svg" with { type: "text" };
import faInstagram from "@fortawesome/fontawesome-free/svgs/brands/instagram.svg" with { type: "text" };
import faFacebook from "@fortawesome/fontawesome-free/svgs/brands/facebook.svg" with { type: "text" };
import faReddit from "@fortawesome/fontawesome-free/svgs/brands/reddit.svg" with { type: "text" };
import faTwitch from "@fortawesome/fontawesome-free/svgs/brands/twitch.svg" with { type: "text" };
import faDiscord from "@fortawesome/fontawesome-free/svgs/brands/discord.svg" with { type: "text" };
import faTiktok from "@fortawesome/fontawesome-free/svgs/brands/tiktok.svg" with { type: "text" };
import faGlobe from "@fortawesome/fontawesome-free/svgs/solid/globe.svg" with { type: "text" };
import faEnvelope from "@fortawesome/fontawesome-free/svgs/solid/envelope.svg" with { type: "text" };
import faRss from "@fortawesome/fontawesome-free/svgs/solid/rss.svg" with { type: "text" };

type PublicAuthorProfile = {
  name: string;
  links: Record<string, string>;
  avatar: string | null;
};

// Public per-post version metadata (no hash; just the most recent builtAt).
// Mirrors shared/publicPostVersions.ts. See `/assets/post-versions.json`.
type PublicPostVersion = { lastUpdated: string };

type LinkPresentation = { label: string; svg: string };

// Display label + icon for a known link key. Aliases map onto the same icon
// (twitter→X, web→website). Unknown keys fall back to a plain text anchor —
// the author can add a custom key without breaking the byline.
const LINK_PRESENTATION: Record<string, LinkPresentation> = {
  x: { label: "X", svg: faXTwitter },
  twitter: { label: "X", svg: faXTwitter },
  github: { label: "GitHub", svg: faGithub },
  bluesky: { label: "Bluesky", svg: faBluesky },
  mastodon: { label: "Mastodon", svg: faMastodon },
  linkedin: { label: "LinkedIn", svg: faLinkedin },
  youtube: { label: "YouTube", svg: faYoutube },
  threads: { label: "Threads", svg: faThreads },
  instagram: { label: "Instagram", svg: faInstagram },
  facebook: { label: "Facebook", svg: faFacebook },
  reddit: { label: "Reddit", svg: faReddit },
  twitch: { label: "Twitch", svg: faTwitch },
  discord: { label: "Discord", svg: faDiscord },
  tiktok: { label: "TikTok", svg: faTiktok },
  website: { label: "Website", svg: faGlobe },
  web: { label: "Website", svg: faGlobe },
  email: { label: "Email", svg: faEnvelope },
  rss: { label: "RSS", svg: faRss },
};

export function normalizePath(pathname: string): string {
  // Map paths consistently with the build's keys (`/posts/<slug>`): drop a
  // trailing slash, and never key on a bare `/`.
  if (pathname.length > 1 && pathname.endsWith("/")) return pathname.slice(0, -1);
  return pathname;
}

// Format an ISO timestamp as "Last updated May 31, 2026". Falls back to the
// raw ISO if parsing fails — better an awkward date than no date.
export function formatLastUpdated(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  try {
    return d.toLocaleDateString(undefined, {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return d.toISOString().slice(0, 10);
  }
}

// Article meta strip — shown directly above the byline (and, in the future,
// home to the slideshow-mode toggle and other consumption-mode controls). Kept
// separate from the byline because the two are different concerns: this is
// metadata *about the article*, the byline is metadata *about the author*.
// Conflating them was forcing the byline's text column taller than the 48px
// avatar; splitting them lets the byline shrink back to identity-only.
export function buildPostMeta(version: PublicPostVersion | null): HTMLElement | null {
  if (!version?.lastUpdated) return null;
  const meta = document.createElement("div");
  meta.className = "post-meta";
  const label = document.createElement("span");
  label.className = "post-meta-label";
  label.textContent = "Last updated ";
  const time = document.createElement("time");
  time.className = "post-meta-updated";
  // Machine-readable datetime stays the original ISO; the text is human-formatted.
  time.dateTime = version.lastUpdated;
  time.textContent = formatLastUpdated(version.lastUpdated);
  meta.appendChild(label);
  meta.appendChild(time);
  return meta;
}

// Build one social-link anchor with the inline icon (or text fallback for
// unknown keys). Shared by the byline at the top of the post and the follow-
// CTA at the bottom so both stay byte-identical in markup and CSS surface;
// only the parent class differs.
function buildLinkAnchor(key: string, href: string, parentClass: string): HTMLAnchorElement {
  const a = document.createElement("a");
  a.className = `${parentClass}-link ${parentClass}-link-${key}`;
  a.href = href;
  a.target = "_blank";
  // `author`/`me` mark this as the author's own identity link; `noopener`
  // for the new tab.
  a.rel = "author me noopener";
  const preset = LINK_PRESENTATION[key];
  const label = preset?.label ?? key;
  // Tooltip + accessible name on the anchor itself, so the icon-only link
  // is readable to screen readers and hover-discoverable to sighted users.
  a.setAttribute("aria-label", label);
  a.title = label;
  if (preset) {
    // Inline SVG (from FontAwesome, fill="currentColor") so the icon
    // inherits text color and there's no extra network fetch — no webfont,
    // no separate image asset, nothing for CSP to govern.
    a.innerHTML = preset.svg;
    const svgEl = a.querySelector("svg");
    if (svgEl) {
      svgEl.setAttribute("aria-hidden", "true");
      svgEl.setAttribute("focusable", "false");
      svgEl.classList.add(`${parentClass}-icon`);
    }
  } else {
    a.textContent = label;
  }
  return a;
}

export function buildByline(profile: PublicAuthorProfile): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "byline";
  wrap.setAttribute("role", "group");
  wrap.setAttribute("aria-label", "Author");

  if (profile.avatar) {
    const img = document.createElement("img");
    img.className = "byline-avatar";
    img.src = profile.avatar;
    img.width = 48;
    img.height = 48;
    img.alt = profile.name;
    // Above the fold (top of the article) — load eagerly; lazy would defer a
    // ~2.5 KB WebP that's in the first viewport. The follow-CTA avatar below
    // stays lazy (bottom of the post).
    img.loading = "eager";
    img.decoding = "async";
    wrap.appendChild(img);
  }

  const text = document.createElement("div");
  text.className = "byline-text";

  const name = document.createElement("span");
  name.className = "byline-name";
  name.textContent = profile.name;
  text.appendChild(name);

  const linkKeys = Object.keys(profile.links);
  if (linkKeys.length > 0) {
    const links = document.createElement("span");
    links.className = "byline-links";
    for (const key of linkKeys) {
      const href = profile.links[key];
      if (!href) continue;
      links.appendChild(buildLinkAnchor(key, href, "byline"));
    }
    text.appendChild(links);
  }

  wrap.appendChild(text);
  return wrap;
}

// Follow-the-author CTA appended at the bottom of every post. Same data as
// the byline (no second fetch), but a larger, card-styled presentation so it
// reads as a call-to-action rather than identity metadata. Renders nothing
// if the author has no follow links — no point inviting a reader to follow
// when there's nowhere to go. Markup uses only div/span/a/img (not P/H*/etc.)
// so the comments layer's block walker doesn't index it as a commentable
// segment — same constraint that already shapes buildByline.
export function buildFollowCta(profile: PublicAuthorProfile): HTMLElement | null {
  const linkKeys = Object.keys(profile.links).filter((k) => profile.links[k]);
  if (linkKeys.length === 0) return null;

  const wrap = document.createElement("div");
  wrap.className = "author-cta";
  wrap.setAttribute("role", "complementary");
  wrap.setAttribute("aria-label", "Follow the author");

  if (profile.avatar) {
    const img = document.createElement("img");
    img.className = "author-cta-avatar";
    img.src = profile.avatar;
    img.width = 72;
    img.height = 72;
    img.alt = profile.name;
    img.loading = "lazy";
    img.decoding = "async";
    wrap.appendChild(img);
  }

  const text = document.createElement("div");
  text.className = "author-cta-text";

  const headline = document.createElement("div");
  headline.className = "author-cta-headline";
  headline.textContent = "Enjoyed this post?";
  text.appendChild(headline);

  const sub = document.createElement("div");
  sub.className = "author-cta-sub";
  const subPrefix = document.createElement("span");
  subPrefix.className = "author-cta-sub-prefix";
  subPrefix.textContent = "Follow ";
  const subName = document.createElement("span");
  subName.className = "author-cta-name";
  subName.textContent = profile.name;
  sub.appendChild(subPrefix);
  sub.appendChild(subName);
  text.appendChild(sub);

  const links = document.createElement("div");
  links.className = "author-cta-links";
  for (const key of linkKeys) {
    links.appendChild(buildLinkAnchor(key, profile.links[key]!, "author-cta"));
  }
  text.appendChild(links);

  wrap.appendChild(text);
  return wrap;
}

// "Built with presidocs" engine attribution, appended after the follow-CTA.
// Always present (no per-blog data), so the markup is stable and the styling
// is owned by base.css — a downstream blog that wants it gone can hide it with
// a single CSS override. Subtle by design: muted-text-color, small font, no
// border or card framing. Kept dependency-free (no SVG icon) so the attribution
// is a single text-and-anchor row that survives any stylesheet stripping.
export function buildEngineAttribution(): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "engine-attribution";
  wrap.setAttribute("role", "contentinfo");
  wrap.setAttribute("aria-label", "Built with presidocs");
  const prefix = document.createElement("span");
  prefix.textContent = "Built with ";
  const link = document.createElement("a");
  link.className = "engine-attribution-link";
  link.href = "https://github.com/SebastienGllmt/presidocs";
  link.target = "_blank";
  // `noopener` for the new-tab anchor; no `nofollow` — the attribution is a
  // genuine "powered by" credit, not user-generated content.
  link.rel = "noopener";
  link.textContent = "presidocs";
  wrap.appendChild(prefix);
  wrap.appendChild(link);
  return wrap;
}

/**
 * Mount the byline, post-meta strip, follow-CTA, and engine attribution
 * into the article root using the placement rules documented inline.
 * Exported so the unit tests can drive it without standing up the
 * `fetch` round trip.
 *
 *   - Byline: under `#lede` if present, else under `#title`, else
 *     prepended to the article.
 *   - Post-meta strip: directly after `#title` when present, else
 *     prepended. The strip is omitted entirely when no `lastUpdated` is
 *     available (rather than rendering "Last updated undefined").
 *   - Follow-CTA + engine attribution: always appended at the end.
 *     CTA only when at least one social link is present; attribution
 *     unconditional.
 *
 * Idempotent against the same article: callers should check
 * `article.querySelector(".byline")` before invoking; this function does
 * NOT re-check (so a fixture test can mount multiple times in a row to
 * verify idempotence at the call-site level rather than here).
 */
export function mountBylineInto(
  article: HTMLElement,
  profile: PublicAuthorProfile,
  version: PublicPostVersion | null,
): void {
  const byline = buildByline(profile);
  const postMeta = buildPostMeta(version);
  const lede = article.querySelector("#lede");
  const title = article.querySelector("#title");

  // The build serves a fixed-height reserve placeholder where each element
  // mounts (shared/articleChromeReserve.ts, applied by the bunHtmlHeadPlugin in
  // both dev and prod); base.css gives the reserve the same box as the real
  // element, so swapping it in is a single zero-shift layout pass — killing the
  // article reflow Lighthouse's `cls-culprits-insight` attributed to this client
  // insert. The sibling-insert path below is the fallback when no reserve is
  // present. The reserve class (`.byline-reserve`) is distinct from `.byline`,
  // so the `boot()` idempotence guard never mistakes the empty placeholder for a
  // populated byline.
  const bylineReserve = article.querySelector(".byline-reserve");
  if (bylineReserve) bylineReserve.replaceWith(byline);
  // Byline keeps its old slot — under the lede if present, else under the title.
  else if (lede) lede.after(byline);
  else if (title) title.after(byline);
  else article.prepend(byline);

  // Post-meta sits *directly under the <h1> title* — where readers expect
  // "date / reading time / mode toggle" type info on a blog. With a lede this
  // separates the title from its lede with the date row, which is the standard
  // pattern (NYT/Guardian/Substack). Insertion is `title.after(postMeta)` AFTER
  // the byline insertion above — so in the no-lede case where both share the
  // title anchor, DOM order is title → postMeta → byline (each .after() inserts
  // as the title's *immediate* next sibling, pushing the previous insertion
  // down).
  const postMetaReserve = article.querySelector(".post-meta-reserve");
  if (postMetaReserve) {
    // A reserve is emitted only when the build had a version; if the client
    // somehow lacks one, drop the placeholder rather than leave a blank strip.
    if (postMeta) postMetaReserve.replaceWith(postMeta);
    else postMetaReserve.remove();
  } else if (postMeta) {
    if (title) title.after(postMeta);
    else article.prepend(postMeta);
  }

  // Follow-CTA at the bottom of the article — same data, prominent
  // presentation. Appended last so it sits as the final block after the
  // closing paragraph. Null when the profile has no social links — no
  // point inviting a reader to follow when there's nowhere to go.
  const cta = buildFollowCta(profile);
  if (cta) article.appendChild(cta);

  // Engine attribution after the CTA — subtle "Built with presidocs" line.
  // Independent of the author profile (no data dependency), so it always
  // renders.
  article.appendChild(buildEngineAttribution());
}

async function boot(): Promise<void> {
  // Same article-root selector the comments layer uses; present on every post
  // (kept even on narration opt-out posts).
  const article = document.querySelector<HTMLElement>("[data-narration-src]");
  if (!article) return;
  // Idempotent — never render two bylines.
  if (article.querySelector(".byline")) return;

  // Private blogs inline THIS post's byline data into its own (capability-
  // protected) HTML — see generate/strip-served-html.ts:injectBylineData — so
  // the byline never fetches the global /assets/{authors,post-versions}.json
  // maps, which enumerate every post path and are suppressed on a private
  // blog. Prefer the inline element when present (strictly less data, one
  // fewer round-trip). Public posts have no such element and fall through to
  // the fetch below, unchanged.
  const inline = document.getElementById("presidocs-byline-data");
  if (inline) {
    try {
      const d = JSON.parse(inline.textContent ?? "") as PublicAuthorProfile & {
        lastUpdated: string | null;
      };
      if (d.name) {
        mountBylineInto(
          article,
          { name: d.name, links: d.links, avatar: d.avatar },
          d.lastUpdated ? { lastUpdated: d.lastUpdated } : null,
        );
      }
    } catch {
      /* malformed inline data — render nothing rather than a wrong byline */
    }
    return;
  }

  // Both maps key by post path. Fetched in parallel — the byline never blocks
  // on the date (it renders without one if the file is missing).
  const [authorsRes, versionsRes] = await Promise.allSettled([
    fetch("/assets/authors.json", { credentials: "omit" }),
    fetch("/assets/post-versions.json", { credentials: "omit" }),
  ]);

  let map: Record<string, PublicAuthorProfile>;
  try {
    if (authorsRes.status !== "fulfilled" || !authorsRes.value.ok) return;
    map = (await authorsRes.value.json()) as Record<string, PublicAuthorProfile>;
  } catch {
    return;
  }

  let versions: Record<string, PublicPostVersion> = {};
  if (versionsRes.status === "fulfilled" && versionsRes.value.ok) {
    try {
      versions = (await versionsRes.value.json()) as Record<string, PublicPostVersion>;
    } catch {
      versions = {};
    }
  }

  const postPath = normalizePath(location.pathname);
  const profile = map[postPath];
  if (!profile || !profile.name) return;
  const version = versions[postPath] ?? null;

  mountBylineInto(article, profile, version);
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", () => void boot());
} else {
  void boot();
}
