// Build-time generator: emits `.generated/episodeAudio.ts`, a `slug → current
// content-addressed audio URL` map (e.g. `/generated/<slug>/full.<hash>.mp3`),
// read from each post's narration manifest.
//
// The prod Worker imports this map to resolve the STABLE shareable URL
// `/generated/<slug>/episode.<ext>` to the live hashed asset at request time
// (server/createWorker.ts — see proposals/32-stable-shareable-audio-url.md).
// Dev needs no map: its static handler globs the directory for the current
// `full.<hash>.<ext>` (createDevServer.ts), exactly as it already does for the
// bare `manifest.json`.
//
// Reads from `generated/<slug>/` (produced by `bun run generate`, which exists
// before `bun run build` runs this). Idempotent: byte-identical output when the
// audio set is unchanged.

import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { resolveBlogPaths } from "../shared/blogPaths.ts";
import { findManifestName } from "../shared/manifestFile.ts";

const paths = resolveBlogPaths();

async function main(): Promise<void> {
  console.log("Generating episode audio map…");

  const out: Record<string, { audio: string; digest?: string }> = {};
  let slugs: string[] = [];
  try {
    const entries = await readdir(paths.generatedDir, { withFileTypes: true });
    slugs = entries
      .filter((e) => e.isDirectory() && !e.name.startsWith("."))
      .map((e) => e.name)
      .sort();
  } catch {
    // No generated/ dir → no audio posts. Still emit an (empty) map so the
    // content repo's worker.ts import resolves and typechecks.
  }

  for (const slug of slugs) {
    const dir = join(paths.generatedDir, slug);
    const manifestName = await findManifestName(dir);
    if (!manifestName) continue;
    let audio: unknown;
    let digest: unknown;
    try {
      const m = (await Bun.file(join(dir, manifestName)).json()) as {
        audio?: unknown;
        audioDigest?: unknown;
      };
      audio = m.audio;
      digest = m.audioDigest;
    } catch {
      continue; // malformed manifest → no stable URL for this post
    }
    if (typeof audio === "string" && audio) {
      out[slug] = { audio };
      if (typeof digest === "string" && digest) out[slug]!.digest = digest;
      console.log(`  ${slug} → ${audio}`);
    }
  }

  const entriesSrc = Object.keys(out)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])},`)
    .join("\n");

  const tsOut = `// AUTO-GENERATED by generate/episode-audio.ts. DO NOT EDIT.
// Regenerated as part of \`bun run build\`. Maps each post slug to its current
// content-addressed audio URL; the Worker resolves the stable
// \`/generated/<slug>/episode.<ext>\` URL against this (see server/createWorker.ts).
// Self-contained (no engine import) so it stays portable across content repos;
// the structural type is checked where the engine consumes it.

export const EPISODE_AUDIO: Record<string, { audio: string; digest?: string }> = {
${entriesSrc}
};
`;

  await mkdir(dirname(paths.episodeAudioMap), { recursive: true });
  await writeFile(paths.episodeAudioMap, tsOut, "utf8");
  console.log(
    `Wrote ${relative(paths.contentRoot, paths.episodeAudioMap)} (${Object.keys(out).length} episode(s))`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
