// Build-time generator: walks `posts/*.html`, computes SHA-256 of
// each post's source bytes, updates the committed `posts/versions.json`
// history (prepending a new entry whenever the hash changed since the
// last build), and emits `server/postVersions.generated.ts` for the
// Worker to import at module load.
//
// Idempotent — running twice without editing any post is a no-op on
// disk and produces a byte-identical generated TS file.

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import {
  sha256Hex,
  type PostVersion,
  type PostVersionRecord,
} from "../server/postVersions.ts";

const ROOT = resolve(import.meta.dir, "..");
const POSTS_DIR = join(ROOT, "posts");
const HISTORY_PATH = join(POSTS_DIR, "versions.json");
const OUT_PATH = join(ROOT, "server", "postVersions.generated.ts");

type HistoryFile = Record<string, PostVersion[]>;

async function walk(
  rootDir: string,
  currentDir: string,
  out: Record<string, string>, // postPath -> currentHash
): Promise<void> {
  const entries = await readdir(currentDir, { withFileTypes: true });
  for (const ent of entries) {
    const full = join(currentDir, ent.name);
    if (ent.isDirectory()) {
      await walk(rootDir, full, out);
    } else if (ent.isFile() && ent.name.endsWith(".html")) {
      // AI-assisted authoring writes drafts as a sibling sidecar
      // (`posts/<slug>.ai-draft.html`). Skip them — they're not real
      // posts and versioning them would pollute `versions.json` with
      // phantom postPaths every time someone built mid-review.
      if (ent.name.endsWith(".ai-draft.html")) continue;
      const bytes = await readFile(full);
      const hash = await sha256Hex(bytes);
      const relPath = relative(rootDir, full).split(sep).join("/");
      const noExt = relPath.replace(/\.html$/, "");
      const postPath = `/posts/${noExt}`;
      out[postPath] = hash;
      console.log(`  ${postPath} → ${hash.slice(0, 12)}…`);
    }
  }
}

async function loadHistory(): Promise<HistoryFile> {
  try {
    const text = await readFile(HISTORY_PATH, "utf8");
    return JSON.parse(text) as HistoryFile;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return {};
    throw err;
  }
}

async function main(): Promise<void> {
  console.log("Generating post versions…");
  const current: Record<string, string> = {};
  await walk(POSTS_DIR, POSTS_DIR, current);

  const history = await loadHistory();
  let mutated = false;
  const now = new Date().toISOString();

  for (const [postPath, hash] of Object.entries(current)) {
    const existing = history[postPath] ?? [];
    if (existing.length === 0 || existing[0]!.hash !== hash) {
      history[postPath] = [{ hash, builtAt: now }, ...existing];
      mutated = true;
      console.log(`  [new] ${postPath} version ${hash.slice(0, 12)}…`);
    }
  }

  if (mutated) {
    // Stable key order for the JSON write so git diffs are minimal.
    const sortedHistory: HistoryFile = {};
    for (const k of Object.keys(history).sort()) sortedHistory[k] = history[k]!;
    await writeFile(
      HISTORY_PATH,
      JSON.stringify(sortedHistory, null, 2) + "\n",
      "utf8",
    );
    console.log(`Wrote ${relative(ROOT, HISTORY_PATH)}`);
  } else {
    console.log("History unchanged.");
  }

  // Emit the generated TS file (always — keeps it in sync with the
  // current set of posts even if no hash changed).
  const out: Record<string, PostVersionRecord> = {};
  for (const postPath of Object.keys(current).sort()) {
    out[postPath] = {
      currentHash: current[postPath]!,
      history: history[postPath] ?? [],
    };
  }

  const entriesSrc = Object.entries(out)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");

  const tsOut = `// AUTO-GENERATED by generate/post-versions.ts. DO NOT EDIT.
// Regenerated as part of \`bun run build\`. Source of truth is the
// per-post SHA-256 of source HTML; history accumulates in
// posts/versions.json (also generator-managed).

import type { PostVersionRecord } from "./postVersions.ts";

export const POST_VERSIONS: Record<string, PostVersionRecord> = {
${entriesSrc}
};
`;

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, tsOut, "utf8");
  console.log(
    `Wrote ${relative(ROOT, OUT_PATH)} (${Object.keys(out).length} post(s))`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
