// Build-time codegen for the DEV server's static route table. Scans the
// content repo's posts/*.html (recursively) plus its landing index.html and
// emits `.generated/postRoutes.ts` exporting a `staticRoutes` map of URL path
// → imported HTML bundle.
//
// Why a codegen rather than hand-written imports in index.ts: Bun's bundler/HMR
// needs the HTML imports to be *static* (it can't follow a runtime glob), but
// we also don't want every content repo to hand-maintain a route list. So we
// generate the static-import module from the filesystem — drop a post in
// posts/, re-run (the `dev` script does this for you), and it's mounted.
//
// Dev-only: the production build bundles posts directly via `bun build
// ./posts/*.html`, so this map never ships to the Worker.
//
// Idempotent — running twice without adding a post produces byte-identical
// output (entries are sorted).

import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { resolveBlogPaths } from "../shared/blogPaths.ts";

const paths = resolveBlogPaths();

type RouteEntry = { importName: string; importPath: string; urlPath: string };

// Turn a post slug/relpath into a valid, collision-resistant JS identifier.
function toIdent(relPathNoExt: string, used: Set<string>): string {
  let base = relPathNoExt
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (!base || /^[0-9]/.test(base)) base = `post_${base}`;
  let name = base;
  let i = 1;
  while (used.has(name)) name = `${base}_${i++}`;
  used.add(name);
  return name;
}

async function exists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function walkPosts(
  rootDir: string,
  currentDir: string,
  out: string[],
): Promise<void> {
  let entries;
  try {
    entries = await readdir(currentDir, { withFileTypes: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return;
    throw err;
  }
  for (const ent of entries) {
    const full = join(currentDir, ent.name);
    if (ent.isDirectory()) await walkPosts(rootDir, full, out);
    else if (ent.isFile() && ent.name.endsWith(".html")) out.push(full);
  }
}

async function main(): Promise<void> {
  console.log("Generating dev post routes…");
  const used = new Set<string>();
  const routes: RouteEntry[] = [];

  // Landing page at "/", if the content repo has one.
  const landing = join(paths.contentRoot, "index.html");
  if (await exists(landing)) {
    routes.push({
      importName: "landing",
      importPath: relative(paths.generatedMapsDir, landing).split(sep).join("/"),
      urlPath: "/",
    });
    used.add("landing");
  }

  const postFiles: string[] = [];
  await walkPosts(paths.postsDir, paths.postsDir, postFiles);
  postFiles.sort();
  for (const full of postFiles) {
    const relNoExt = relative(paths.postsDir, full)
      .split(sep)
      .join("/")
      .replace(/\.html$/, "");
    routes.push({
      importName: toIdent(relNoExt, used),
      importPath: relative(paths.generatedMapsDir, full).split(sep).join("/"),
      urlPath: `/posts/${relNoExt}`,
    });
  }

  const imports = routes
    .map((r) => `import ${r.importName} from ${JSON.stringify(r.importPath)};`)
    .join("\n");
  const mapEntries = routes
    .map((r) => `  ${JSON.stringify(r.urlPath)}: ${r.importName},`)
    .join("\n");

  const out = `// AUTO-GENERATED by generate/post-routes.ts. DO NOT EDIT.
// Dev-only static route table for the Bun dev server (see createDevServer.ts).
// Regenerated by the \`dev\` script. Source of truth is the content repo's
// index.html + posts/*.html.

export const staticRoutes: Record<string, Bun.HTMLBundle> = {
${mapEntries}
};
`;

  await mkdir(paths.generatedMapsDir, { recursive: true });
  await writeFile(paths.postRoutesFile, `${imports}\n\n${out}`, "utf8");
  console.log(
    `  Wrote ${relative(paths.contentRoot, paths.postRoutesFile)} (${routes.length} route(s))`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
