// Build-time generator: walks `posts/*.html`, computes SHA-256 of
// each post's source bytes, updates the committed `posts/versions.json`
// history (prepending a new entry whenever the hash changed since the
// last build), and emits `server/postVersions.generated.ts` for the
// Worker to import at module load.
//
// Idempotent — running twice without editing any post is a no-op on
// disk and produces a byte-identical generated TS file.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, sep } from "node:path";
import {
  sha256Hex,
  type PostVersion,
  type PostVersionRecord,
} from "../server/postVersions.ts";
import { resolveBlogPaths } from "../shared/blogPaths.ts";
import { collectHtmlFiles } from "../shared/walkHtml.ts";

const paths = resolveBlogPaths();
const POSTS_DIR = paths.postsDir;
const HISTORY_PATH = paths.versionsJson;
const OUT_PATH = paths.postVersionsMap;

type HistoryFile = Record<string, PostVersion[]>;

// Hash every `*.html` under `rootDir` into `out` (postPath -> currentHash).
// Throws on a missing rootDir (a missing posts/ at build time is a real error).
async function hashPostsInto(
  rootDir: string,
  out: Record<string, string>,
): Promise<void> {
  for (const full of collectHtmlFiles(rootDir)) {
    const bytes = await readFile(full);
    const hash = await sha256Hex(bytes);
    const relPath = relative(rootDir, full).split(sep).join("/");
    const noExt = relPath.replace(/\.html$/, "");
    const postPath = `/posts/${noExt}`;
    out[postPath] = hash;
    console.log(`  ${postPath} → ${hash.slice(0, 12)}…`);
  }
}

async function loadHistory(): Promise<HistoryFile> {
  try {
    const text = await readFile(HISTORY_PATH, "utf8");
    return JSON.parse(text) as HistoryFile;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return {};
    throw err;
  }
}

async function main(): Promise<void> {
  console.log("Generating post versions…");
  const current: Record<string, string> = {};
  await hashPostsInto(POSTS_DIR, current);

  const history = await loadHistory();
  let mutated = false;
  const now = new Date().toISOString();

  for (const [postPath, hash] of Object.entries(current)) {
    const existing = history[postPath] ?? [];
    if (existing.length === 0 || existing[0]!.hash !== hash) {
      history[postPath] = [{ hash, builtAt: now }, ...existing];
      mutated = true;
      console.log(`  [new] ${postPath} version ${hash.slice(0, 12)}…`);
    }
  }

  if (mutated) {
    // Stable key order for the JSON write so git diffs are minimal.
    const sortedHistory: HistoryFile = {};
    for (const k of Object.keys(history).sort()) sortedHistory[k] = history[k]!;
    await mkdir(dirname(HISTORY_PATH), { recursive: true });
    await writeFile(
      HISTORY_PATH,
      JSON.stringify(sortedHistory, null, 2) + "\n",
      "utf8",
    );
    console.log(`Wrote ${relative(paths.contentRoot, HISTORY_PATH)}`);
  } else {
    console.log("History unchanged.");
  }

  // Emit the generated TS file (always — keeps it in sync with the
  // current set of posts even if no hash changed).
  const out: Record<string, PostVersionRecord> = {};
  for (const postPath of Object.keys(current).sort()) {
    out[postPath] = {
      currentHash: current[postPath]!,
      history: history[postPath] ?? [],
    };
  }

  const entriesSrc = Object.entries(out)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");

  const tsOut = `// AUTO-GENERATED by generate/post-versions.ts. DO NOT EDIT.
// Regenerated as part of \`bun run build\`. Source of truth is the
// per-post SHA-256 of source HTML; history accumulates in
// posts/versions.json (also generator-managed).
// Self-contained (no engine import) so it's portable across content repos;
// the structural type is checked where the engine consumes it.

export const POST_VERSIONS: Record<
  string,
  { currentHash: string; history: { hash: string; builtAt: string }[] }
> = {
${entriesSrc}
};
`;

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, tsOut, "utf8");
  console.log(
    `Wrote ${relative(paths.contentRoot, OUT_PATH)} (${Object.keys(out).length} post(s))`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
