// Build-time generator: scans `posts/*.html` for the
// `<meta name="author-email" content="...">` tag and emits
// `server/postMeta.generated.ts` — a static TypeScript module the
// Worker imports.
//
// Why a build step rather than runtime parsing on the Worker side: the
// Worker has no filesystem, and parsing HTML via the ASSETS binding on
// every author-check is per-request overhead for data that only
// changes when a post is published. Baking the map into the Worker
// bundle eliminates the per-request cost.
//
// Run via `bun run build` (which chains this script before
// `bun build`). Idempotent — running twice produces the same output.

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { parseAuthorEmailFromHtml } from "../server/postMeta.ts";
import { resolveBlogPaths } from "../shared/blogPaths.ts";

const paths = resolveBlogPaths();
const POSTS_DIR = paths.postsDir;
const OUT_PATH = paths.postMetaMap;

async function walk(
  rootDir: string,
  currentDir: string,
  out: Record<string, { authorEmail: string }>,
): Promise<void> {
  const entries = await readdir(currentDir, { withFileTypes: true });
  for (const ent of entries) {
    const full = join(currentDir, ent.name);
    if (ent.isDirectory()) {
      await walk(rootDir, full, out);
    } else if (ent.isFile() && ent.name.endsWith(".html")) {
      const html = await readFile(full, "utf8");
      const email = parseAuthorEmailFromHtml(html);
      if (!email) {
        console.warn(`  [skip] ${ent.name} — no <meta name="author-email">`);
        continue;
      }
      const relPath = relative(rootDir, full).split(sep).join("/");
      const noExt = relPath.replace(/\.html$/, "");
      const postPath = `/posts/${noExt}`;
      out[postPath] = { authorEmail: email };
      console.log(`  ${postPath} → ${email}`);
    }
  }
}

async function main(): Promise<void> {
  console.log("Generating post meta…");
  const map: Record<string, { authorEmail: string }> = {};
  await walk(POSTS_DIR, POSTS_DIR, map);

  // Stable key order so the generated file is byte-identical between
  // runs (helps with git diffs / build caching).
  const keys = Object.keys(map).sort();
  const entriesSrc = keys
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
    .join("\n");

  const out = `// AUTO-GENERATED by generate/post-meta.ts. DO NOT EDIT.
// Regenerated as part of \`bun run build\`. Source of truth is the
// <meta name="author-email"> tag in each posts/*.html file.
// Self-contained (no engine import) so it's portable across content repos;
// the structural type is checked where the engine consumes it.

export const POST_AUTHORS: Record<string, { authorEmail: string }> = {
${entriesSrc}
};
`;

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, out, "utf8");
  console.log(`Wrote ${relative(paths.contentRoot, OUT_PATH)} (${keys.length} post(s))`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
