// Build-time generator: scans `posts/*.html` for the
// `<meta name="author-email" content="...">` tag and emits
// `server/postMeta.generated.ts` — a static TypeScript module the
// Worker imports.
//
// Why a build step rather than runtime parsing on the Worker side: the
// Worker has no filesystem, and parsing HTML via the ASSETS binding on
// every author-check is per-request overhead for data that only
// changes when a post is published. Baking the map into the Worker
// bundle eliminates the per-request cost.
//
// Run via `bun run build` (which chains this script before
// `bun build`). Idempotent — running twice produces the same output.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, sep } from "node:path";
import { parseAuthorEmailFromHtml } from "../server/postMeta.ts";
import { resolveBlogPaths } from "../shared/blogPaths.ts";
import { collectHtmlFiles } from "../shared/walkHtml.ts";

const paths = resolveBlogPaths();
const POSTS_DIR = paths.postsDir;
const OUT_PATH = paths.postMetaMap;

async function main(): Promise<void> {
  console.log("Generating post meta…");
  const map: Record<string, { authorEmail: string }> = {};
  // Recursive `**/*.html` under posts/ (throws on a missing posts/ — a real
  // build-time misconfiguration). This is the walk the other engine `.html`
  // collectors were modelled on; it now shares the one Bun.Glob helper.
  for (const full of collectHtmlFiles(POSTS_DIR)) {
    const html = await readFile(full, "utf8");
    const relPath = relative(POSTS_DIR, full).split(sep).join("/");
    const email = parseAuthorEmailFromHtml(html);
    if (!email) {
      console.warn(`  [skip] ${relPath} — no <meta name="author-email">`);
      continue;
    }
    const noExt = relPath.replace(/\.html$/, "");
    const postPath = `/posts/${noExt}`;
    map[postPath] = { authorEmail: email };
    console.log(`  ${postPath} → ${email}`);
  }

  // Stable key order so the generated file is byte-identical between
  // runs (helps with git diffs / build caching).
  const keys = Object.keys(map).sort();
  const entriesSrc = keys
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
    .join("\n");

  // The canonical host, baked at build from SITE_URL (null when unset — the
  // same gate every discovery feature uses). The Worker compares request hosts
  // against it to X-Robots-Tag-noindex preview/staging hosts (proposal 16
  // item 6); baking it here avoids duplicating SITE_URL into wrangler vars.
  const siteUrl = (process.env.SITE_URL ?? "").trim();
  let siteHost: string | null = null;
  if (siteUrl) {
    try {
      siteHost = new URL(siteUrl).host;
    } catch {
      console.warn(`  [warn] SITE_URL is not a valid URL (${siteUrl}) — SITE_HOST emitted as null`);
    }
  }

  const out = `// AUTO-GENERATED by generate/post-meta.ts. DO NOT EDIT.
// Regenerated as part of \`bun run build\`. Source of truth is the
// <meta name="author-email"> tag in each posts/*.html file (and SITE_URL for
// the canonical host).
// Self-contained (no engine import) so it's portable across content repos;
// the structural type is checked where the engine consumes it.

export const POST_AUTHORS: Record<string, { authorEmail: string }> = {
${entriesSrc}
};

// Host of the canonical SITE_URL at build time, or null when SITE_URL was
// unset. The Worker noindexes responses served from any other host.
export const SITE_HOST: string | null = ${JSON.stringify(siteHost)};
`;

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, out, "utf8");
  console.log(`Wrote ${relative(paths.contentRoot, OUT_PATH)} (${keys.length} post(s))`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
