// Build step: emit site-level discovery artifacts that sit beside per-post
// structured data and feeds. These three files are how crawlers, search
// engines, and LLM indexers learn the *site as a whole* — independent of any
// single post:
//
//   dist/robots.txt   Crawler allow signal + sitemap pointer + AI-crawler
//                     stance (configurable via ROBOTS_AI_CRAWLERS=allow|deny).
//   dist/sitemap.xml  Canonical URL set with <lastmod> from versions.json.
//   dist/llms.txt     LLM-friendly site map (llmstxt.org convention) —
//                     one-line site summary + curated post index.
//
// Site-level analogue of generate/feeds.ts: same SITE_URL gate (every artifact
// needs absolute URLs), same disk gather (posts/*.html + versions.json +
// landing index.html), same fail-silent posture. Reuses feeds.ts's pure
// helpers — `escapeXml`, `readSiteMeta`, `extractPostMeta` — so the engine
// stays content-agnostic (the site title/description come from the blog's own
// landing page, never hardcoded here).
//
// Run AFTER generate/feeds.ts so we can advertise /podcast.xml in llms.txt
// only when feeds.ts actually emitted it. No ordering dependency the other way.
//
// Served as static assets by env.ASSETS.fetch — no Worker route changes
// needed. robots.txt/llms.txt get text/plain by default; sitemap.xml gets
// application/xml, which every sitemap consumer accepts (no MIME override
// needed, unlike the Atom/RSS .xml special-case in createWorker.ts).

import { readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { resolveBlogPaths } from "../shared/blogPaths.ts";
import { isPrivateBlog } from "../shared/blogPrivacy.ts";
import { resolveFeedConfig } from "./feedConfig.ts";
import { resolveLicenseConfig } from "../shared/licenseConfig.ts";
import { parseAuthorEmailFromHtml } from "../server/postMeta.ts";
import { escapeXml, extractPostMeta, readSiteMeta } from "./feeds.ts";

const paths = resolveBlogPaths();

// ---- pure builders (exported for tests) ------------------------------------

export type RobotsOptions = {
  /**
   * Absolute URL of the sitemap, e.g. `https://blog.example.com/sitemap.xml` —
   * or null to omit the `Sitemap:` line entirely (a private blog emits
   * robots.txt with no sitemap to point at; see methodology → Private blogs).
   */
  sitemapUrl: string | null;
  /**
   * Allow AI crawlers (default, true) or block the named training/answer bots
   * (false). The stance is deliberate and the file calls it out so a future
   * contributor doesn't "lock it down" reflexively. Driven by
   * `ROBOTS_AI_CRAWLERS=allow|deny` in the build env.
   */
  allowAi: boolean;
};

// Common AI training / answer crawlers. Disallowed only when allowAi=false; the
// list is documented inline so it's easy to amend per-bot if a deploy ever
// wants finer-grained control (e.g. allow ClaudeBot but deny CCBot).
const AI_CRAWLER_USER_AGENTS = [
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "ClaudeBot",
  "Claude-Web",
  "anthropic-ai",
  "Google-Extended",
  "PerplexityBot",
  "CCBot",
  "Applebot-Extended",
  "Amazonbot",
  "Bytespider",
  "Meta-ExternalAgent",
] as const;

export function buildRobotsTxt(opts: RobotsOptions): string {
  const lines: string[] = [];
  lines.push("# robots.txt — generated by presidocs/generate/site-discovery.ts.");
  lines.push("# AI-crawler stance is deliberate; flip with ROBOTS_AI_CRAWLERS=allow|deny.");
  lines.push("");
  lines.push("User-agent: *");
  lines.push("Allow: /");
  lines.push("");
  if (!opts.allowAi) {
    lines.push("# ROBOTS_AI_CRAWLERS=deny — block named training/answer crawlers.");
    for (const bot of AI_CRAWLER_USER_AGENTS) {
      lines.push(`User-agent: ${bot}`);
      lines.push("Disallow: /");
      lines.push("");
    }
  }
  if (opts.sitemapUrl !== null) {
    lines.push(`Sitemap: ${opts.sitemapUrl}`);
    lines.push("");
  }
  return lines.join("\n");
}

export type SitemapEntry = {
  /** Absolute URL. */
  loc: string;
  /**
   * `<lastmod>` — W3C date form (`YYYY-MM-DD` or full ISO-8601 datetime; both
   * are valid per sitemaps.org). We pass through whatever versions.json
   * carries (full ISO-8601 timestamps).
   */
  lastmod: string;
};

export function buildSitemapXml(entries: SitemapEntry[]): string {
  const urls = entries
    .map(
      (e) =>
        `<url><loc>${escapeXml(e.loc)}</loc><lastmod>${escapeXml(e.lastmod)}</lastmod></url>`,
    )
    .join("");
  // Deliberately no <changefreq>/<priority> — Google documents that it ignores
  // both, so they'd be pure noise.
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">` +
    urls +
    `</urlset>\n`
  );
}

export type LlmsPost = {
  /**
   * Absolute URL of the post's **Markdown twin** (`/posts/<slug>.md`, emitted by
   * generate/markdown-export.ts). The Posts list links here, not at the HTML
   * page: an LLM indexer lands on clean Markdown with no HTML to parse, which is
   * the whole point of an llms.txt index. The canonical HTML page is still
   * carried by sitemap.xml and each post's `<link rel="canonical">`.
   */
  mdUrl: string;
  title: string;
  summary: string;
};

export type LlmsSite = {
  title: string;
  description: string;
  /**
   * Reuse terms: the content license governs the prose an LLM
   * reads here; the code license governs any snippets. Either null → that part
   * is omitted; both null → no license line at all (no imposed default).
   */
  contentLicense: { id: string; url: string } | null;
  codeLicense: { id: string; url: string } | null;
  /** Absolute feed URLs; podcast may be null when no audio posts exist. */
  feeds: { atom: string; podcast: string | null };
  /**
   * Absolute URL of the engine's "How this blog works" page, or null. Listed in
   * `## Optional` so an LLM answering "how do I subscribe / listen / comment"
   * can fetch one curated page instead of inferring from the posts. Always set
   * when SITE_URL is (generate/help-page.ts emits /help under the same gate).
   */
  helpUrl: string | null;
};

// llmstxt.org convention: a curated Markdown index an LLM indexer can read
// instead of crawling every page. Title heading, one-line site summary as a
// blockquote, then linked post list (one-line description per post).
export function buildLlmsTxt(site: LlmsSite, posts: LlmsPost[]): string {
  const lines: string[] = [];
  lines.push(`# ${site.title || "Blog"}`);
  lines.push("");
  if (site.description) {
    lines.push(`> ${site.description}`);
    lines.push("");
  }
  // Reuse terms, so an LLM reading this index knows whether/how it may reuse the
  // content. Content first (the prose it's about to read), then code samples.
  // Omitted entirely when no content license is declared.
  if (site.contentLicense) {
    const parts = [`[${site.contentLicense.id}](${site.contentLicense.url}) (content)`];
    if (site.codeLicense) {
      parts.push(`[${site.codeLicense.id}](${site.codeLicense.url}) (code samples)`);
    }
    lines.push(`Licensed under ${parts.join(" and ")}.`);
    lines.push("");
  }
  if (posts.length > 0) {
    lines.push("## Posts");
    lines.push("");
    for (const p of posts) {
      const suffix = p.summary ? `: ${p.summary}` : "";
      // Link the Markdown twin (`/posts/<slug>.md`), not the HTML page — see
      // LlmsPost.mdUrl. An LLM following this index gets clean Markdown directly.
      lines.push(`- [${p.title}](${p.mdUrl})${suffix}`);
    }
    lines.push("");
  }
  // `## Optional` is reserved by the llmstxt.org spec — "URLs provided there
  // can be skipped if a shorter context is needed." Subscription endpoints
  // are exactly that: useful context for a tool deciding how to *follow*
  // updates, skippable for a tool just trying to *read* the posts.
  lines.push("## Optional");
  lines.push("");
  lines.push(`- [Atom feed](${site.feeds.atom})`);
  if (site.feeds.podcast) lines.push(`- [Podcast feed](${site.feeds.podcast})`);
  if (site.helpUrl) lines.push(`- [How this blog works](${site.helpUrl})`);
  lines.push("");
  return lines.join("\n");
}

// ---- disk gather -----------------------------------------------------------

type VersionEntry = { hash: string; builtAt: string };

async function main(): Promise<void> {
  const cfg = resolveFeedConfig();
  if (!cfg.baseUrl) {
    console.log("Site discovery: no SITE_URL — skipping.");
    return;
  }
  const baseUrl = cfg.baseUrl;
  const distDir = paths.distDir;
  if (!existsSync(distDir)) {
    console.warn("  dist/ does not exist — run `bun build` first; skipping site discovery.");
    return;
  }

  // versions.json: post path → newest-first [{hash, builtAt}]. Missing/malformed
  // degrades to "sitemap with just the landing page" rather than failing.
  let versions: Record<string, VersionEntry[]> = {};
  try {
    versions = (await Bun.file(paths.versionsJson).json()) as Record<string, VersionEntry[]>;
  } catch {
    versions = {};
  }

  // A "real post" is posts/<slug>.html with an <author-email> meta AND a
  // versions.json record — identical convention to feeds.ts:407-416.
  type GatheredPost = { postPath: string; title: string; summary: string; updated: string };
  const posts: GatheredPost[] = [];
  const postFiles = (await readdir(paths.postsDir)).filter((f) => f.endsWith(".html"));
  for (const file of postFiles) {
    const slug = file.replace(/\.html$/, "");
    const postPath = `/posts/${slug}`;
    const srcHtml = await Bun.file(join(paths.postsDir, file)).text();
    if (!parseAuthorEmailFromHtml(srcHtml)) continue;
    const history = versions[postPath];
    if (!history || history.length === 0) continue;
    const { title, summary } = extractPostMeta(srcHtml);
    posts.push({ postPath, title, summary, updated: history[0]!.builtAt });
  }

  // Newest-first for reader display in llms.txt and stable sitemap order.
  posts.sort((a, b) => (a.updated < b.updated ? 1 : -1));

  // Landing <lastmod> = max(post builtAt). The landing changes when the post
  // list does, so this is a monotonic, no-extra-state proxy. With no posts
  // yet, fall back to the epoch — the file is still valid.
  const landingLastmod = posts[0]?.updated ?? new Date(0).toISOString();

  const sitemapEntries: SitemapEntry[] = [
    { loc: `${baseUrl}/`, lastmod: landingLastmod },
    ...posts.map((p) => ({ loc: `${baseUrl}${p.postPath}`, lastmod: p.updated })),
  ];

  // Private blogs (methodology → Private blogs): robots.txt is still emitted
  // — default-ALLOW with no Sitemap line, because the index-exclusion work is
  // done by the noindex header/meta, and a blanket `Disallow: /` would
  // BACKFIRE: a crawler forbidden from fetching a leaked link never sees the
  // noindex, so the URL can be indexed URL-only. The AI-crawler stance
  // defaults to deny for a private blog (training/answer bots are exactly who
  // it wants gone); an explicit ROBOTS_AI_CRAWLERS still wins either way.
  const privateBlog = isPrivateBlog();
  const sitemapUrl = privateBlog ? null : `${baseUrl}/sitemap.xml`;
  const aiStance = (process.env.ROBOTS_AI_CRAWLERS ?? (privateBlog ? "deny" : "allow"))
    .trim()
    .toLowerCase();
  // Anything other than the explicit deny keeps the default-allow posture.
  const allowAi = aiStance !== "deny";

  await writeFile(
    join(distDir, "robots.txt"),
    buildRobotsTxt({ sitemapUrl, allowAi }),
    "utf8",
  );
  if (privateBlog) {
    // sitemap.xml and llms.txt exist to ENUMERATE posts — the exact thing a
    // capability-URL blog must never do. Nothing else to emit.
    console.log(`Site discovery: dist/robots.txt (AI ${allowAi ? "allow" : "deny"}, no sitemap) — private blog; sitemap.xml/llms.txt suppressed.`);
    return;
  }
  await writeFile(join(distDir, "sitemap.xml"), buildSitemapXml(sitemapEntries), "utf8");

  // llms.txt — points at /podcast.xml only when feeds.ts actually emitted it
  // (an audio-less blog has no podcast feed, by feeds.ts:508-511).
  const podcastUrl = existsSync(join(distDir, "podcast.xml")) ? `${baseUrl}/podcast.xml` : null;
  const meta = await readSiteMeta();
  const license = resolveLicenseConfig();
  const llmsPosts: LlmsPost[] = posts.map((p) => ({
    // The Markdown twin emitted by generate/markdown-export.ts (which runs
    // earlier in `bun run build`), so the file is on disk by serve time.
    mdUrl: `${baseUrl}${p.postPath}.md`,
    title: p.title,
    summary: p.summary,
  }));
  await writeFile(
    join(distDir, "llms.txt"),
    buildLlmsTxt(
      {
        title: meta.title,
        description: meta.description,
        contentLicense: license.content,
        codeLicense: license.code,
        feeds: { atom: `${baseUrl}/feed.xml`, podcast: podcastUrl },
        // /help is emitted by generate/help-page.ts under the same SITE_URL
        // gate this step runs under, so it's always reachable here.
        helpUrl: `${baseUrl}/help`,
      },
      llmsPosts,
    ),
    "utf8",
  );

  console.log(
    `Site discovery: dist/robots.txt (AI ${allowAi ? "allow" : "deny"})` +
      `, dist/sitemap.xml (${sitemapEntries.length} URL${sitemapEntries.length === 1 ? "" : "s"})` +
      `, dist/llms.txt (${posts.length} post${posts.length === 1 ? "" : "s"})`,
  );
}

if (import.meta.main) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
