// Per-post version hash + history.
//
// Each post has a current SHA-256 of its source HTML and a history of
// past hashes with the timestamp at which each first appeared (i.e.
// when `bun run build` first observed it). Commenters use the current
// hash to detect "this doc changed since I last visited" on revisit;
// the author can review the full history to see when changes shipped.
//
// Two construction paths (mirrors postMeta.ts):
//   - dev (Bun): scan `posts/*.html` at startup, read the committed
//     `posts/versions.json` for history — `postVersions.dev.ts`
//   - prod (Workers): import a static map written at build time —
//     `postVersions.generated.ts`, regenerated by `generate/post-versions.ts`
//
// Source of truth for the *history* is `posts/versions.json` (a
// committed file the build script updates in place). Source of truth
// for the *current hash* is the source HTML — recomputed every build
// (and at dev-server startup) so a freshly-saved edit shows up
// immediately even if the JSON hasn't been updated yet.

export type PostVersion = {
  hash: string;
  // ISO 8601 timestamp of the build that first observed this hash.
  builtAt: string;
};

export type PostVersionRecord = {
  currentHash: string;
  // Most recent first. The first entry SHOULD match currentHash; if
  // it doesn't (dev startup observed a fresh hash before the build
  // script ran), the banner still works — history just lags by one.
  history: PostVersion[];
};

export type PostVersionIndex = {
  get(postPath: string): PostVersionRecord | null;
};

// Normalize a path to the canonical post-key form. Both the dev URL
// (`/posts/hash-functions`) and the prod static-asset URL
// (`/posts/hash-functions.html`) resolve to the same key.
export function normalizePostPath(p: string): string {
  // Strip a trailing `/index.html` first (covers an oddly-served dir).
  if (p.endsWith("/index.html")) return p.slice(0, -"/index.html".length);
  if (p.endsWith(".html")) return p.slice(0, -".html".length);
  return p;
}

export function createPostVersionIndex(
  map: Record<string, PostVersionRecord>,
): PostVersionIndex {
  return {
    get(postPath: string): PostVersionRecord | null {
      return map[normalizePostPath(postPath)] ?? null;
    },
  };
}

// SHA-256 hex of arbitrary bytes. Used identically in dev and the
// build script so dev's on-the-fly hash matches what the build will
// eventually persist.
export async function sha256Hex(bytes: ArrayBufferView | ArrayBuffer): Promise<string> {
  const buf = bytes instanceof ArrayBuffer ? bytes : bytes.buffer.slice(
    bytes.byteOffset,
    bytes.byteOffset + bytes.byteLength,
  ) as ArrayBuffer;
  const digest = await crypto.subtle.digest("SHA-256", buf);
  const arr = new Uint8Array(digest);
  let out = "";
  for (let i = 0; i < arr.length; i++) {
    out += arr[i]!.toString(16).padStart(2, "0");
  }
  return out;
}
