// AUTO-GENERATED by generate/post-versions.ts. DO NOT EDIT.
// Regenerated as part of `bun run build`. Source of truth is the
// per-post SHA-256 of source HTML; history accumulates in
// posts/versions.json (also generator-managed).

import type { PostVersionRecord } from "./postVersions.ts";

export const POST_VERSIONS: Record<string, PostVersionRecord> = {
  "/posts/hash-functions": {"currentHash":"a422336815baaa1e50a6684092498677f10d1f02f6fb41afdc77f1bc4eb423e2","history":[{"hash":"a422336815baaa1e50a6684092498677f10d1f02f6fb41afdc77f1bc4eb423e2","builtAt":"2026-05-19T10:08:32.033Z"}]},
};
