// AUTO-GENERATED by generate/post-meta.ts. DO NOT EDIT.
// Regenerated as part of `bun run build`. Source of truth is the
// <meta name="author-email"> tag in each posts/*.html file.

import type { PostMeta } from "./postMeta.ts";

export const POST_AUTHORS: Record<string, PostMeta> = {
  "/posts/hash-functions": {"authorEmail":"sebastiengllmt@gmail.com"},
  "/posts/offer-files": {"authorEmail":"sebastiengllmt@gmail.com"},
};
