// Per-post author metadata. Each post HTML carries its author's email
// in a `<meta name="author-email" content="...">` tag in the head;
// this module is the server-side index that lets auth checks ask "who
// owns this post?" without re-parsing the HTML on every request.
//
// Two construction paths exist, both producing a `PostMetaIndex`:
//   - dev (Bun): scan `posts/*.html` at startup — `postMeta.dev.ts`
//   - prod (Workers): import a static map written at build time —
//     `postMeta.generated.ts`, regenerated by `generate/post-meta.ts`
//
// Why the meta is in the HTML (not a sidecar JSON): the post is the
// single source of truth for authoring (see methodology — "one file per
// post"). The author editing the post sees the email field in the same
// document they're editing the content of.
//
// Spam consideration: the email is currently visible in the served
// HTML. If crawler-spam becomes a problem, the future fix is "strip
// the meta tag from served HTML at build time while keeping it in
// source" — a one-line change to the build script. Server-side
// resolution doesn't depend on the tag being in the response.

export type PostMeta = {
  authorEmail: string;
};

export type PostMetaIndex = {
  // Returns null when the post has no `<meta name="author-email">`,
  // or when the post path isn't known. Callers must treat null as
  // "no author can be matched" — every author-only operation rejects.
  get(postPath: string): PostMeta | null;
};

export function createPostMetaIndex(
  map: Record<string, PostMeta>,
): PostMetaIndex {
  // Defensive copy + lowercased emails for compare-friendliness.
  const normalized: Record<string, PostMeta> = {};
  for (const [k, v] of Object.entries(map)) {
    normalized[k] = { authorEmail: v.authorEmail.trim().toLowerCase() };
  }
  return {
    get(postPath: string): PostMeta | null {
      return normalized[postPath] ?? null;
    },
  };
}

// Parse the author-email out of a post's `<meta name="author-email">`.
// Used by the dev scanner and the build-time generator (never on the hot
// request path — prod imports a static map).
//
// Parsed with HTMLRewriter (a Bun/Workers built-in, lol-html under the hood),
// NOT a regex. This is an authorization input — the answer to "who owns this
// post?" — so soundness matters: a real parser is attribute-order agnostic
// (the spec allows `name` before or after `content`), quote/casing tolerant,
// and immune to the `[^>]*` traps a hand-rolled `<meta …>` regex falls into.
// HTMLRewriter (not linkedom) specifically, because this module is bundled
// into the Cloudflare Worker via createPostMetaIndex() and HTMLRewriter is a
// runtime global — no heavy DOM dependency gets pulled into the worker.
//
// NOTE to future maintainers: do NOT "simplify" this back to a regex. A regex
// over `<meta …>` is unsound (and here, a security regression).
export function parseAuthorEmailFromHtml(html: string): string | null {
  let email: string | null = null;
  new HTMLRewriter()
    .on("meta", {
      element(el) {
        if (email !== null) return; // first match wins (mirrors prior behavior)
        if ((el.getAttribute("name") ?? "").trim().toLowerCase() !== "author-email") return;
        const content = (el.getAttribute("content") ?? "").trim();
        if (content) email = content;
      },
    })
    .transform(html);
  return email;
}

// Helpers for the typical author check that callers do: "is this
// session's verified email the author of this post?" Centralized so
// the comparison rule (case-insensitive, requires email_verified) is
// stated once.
export type AuthorCheckSession = {
  email: string;
  emailVerified: boolean;
};

export function isPostAuthor(
  session: AuthorCheckSession | null | undefined,
  meta: PostMeta | null,
): boolean {
  if (!session || !meta) return false;
  if (!session.emailVerified) return false;
  return session.email.trim().toLowerCase() === meta.authorEmail;
}
