// Service-Worker / PWA tier: registration, app-shell precache, and the
// online → offline navigation fallback (proposal 22 §1 — the highest-value
// real-browser tier, and the reason the harness exists).
//
// This is the tier the fast Bun dev server CANNOT cover: `client/swRegister.ts`
// gates registration on `__BUN_DEV__`, so under plain `bun run dev` the SW never
// registers (dev actively tears down any SW left behind). So this drives the
// **built** worker under `wrangler dev` (`startWranglerServer` = `bun run build`
// + `wrangler dev`), where `dist/sw.js` ships with `__SW_VERSION__` substituted
// and the registration path is live — i.e. exactly what a reader's browser runs.
//
// NOT named `*.e2e.ts` on purpose: like `prodAudioSmoke.ts` it's a heavy tier
// (a full build + wrangler boot), run only via its own script —
// `bun run test:e2e:sw` — never by the default `bun test` or the Chrome
// `test:e2e` lane. `PRESIDOCS_E2E_SKIP_BUILD=1` reuses an existing fresh `dist/`
// for faster local iteration (and to avoid the build's source-rewrite).
//
// Precondition: the harness runs `bun run build`, which rewrites source posts
// (managed <script> tags) + versions.json per normal build behavior — run on an
// ephemeral/CI checkout, or `git checkout` those afterward.
//
// What stays out of scope here (proposal 22 §1, deferred): the cross-deploy
// cache reap (vN → vN+1 needs a second build with a fresh VERSION mid-test) and
// the `cacheFirstRanged` 206 path (covered for the prod Worker by
// `prodAudioSmoke.ts`; the SW's own Range branch awaits a fixture with audio).

import { test, expect, beforeAll, afterAll } from "bun:test";
import type { Browser, BrowserContext, Page } from "playwright";
import { launchChrome, resolveBlogDir, startWranglerServer, type BlogServer } from "./harness.ts";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

let browser: Browser;
let server: BlogServer;
// `dist/sw.js` is the one file the reap test mutates (to simulate a redeploy).
// It's gitignored and regenerated by every build; we still snapshot + restore it
// so reruns (esp. PRESIDOCS_E2E_SKIP_BUILD=1, which reuses dist/) start clean.
let swPath = "";
let swOriginal = "";

beforeAll(async () => {
  [browser, server] = await Promise.all([launchChrome(), startWranglerServer()]);
  swPath = resolve(resolveBlogDir(), "dist", "sw.js");
  swOriginal = readFileSync(swPath, "utf8");
}, 180_000);
afterAll(async () => {
  if (swPath && swOriginal) writeFileSync(swPath, swOriginal); // restore the un-bumped sw.js
  await browser?.close();
  await server?.stop();
});

/**
 * Navigate to `url` and return once the SW *controls* the page. The document
 * that triggers `register()` isn't controlled until the SW claims it, so we wait
 * for `ready` (an active registration), reload once, then wait for a non-null
 * `controller` — after which same-origin navigations run through the SW.
 */
async function loadControlled(ctx: BrowserContext, url: string): Promise<Page> {
  const page = await ctx.newPage();
  await page.goto(url, { waitUntil: "load", timeout: 30_000 });
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.reload({ waitUntil: "load" });
  await page.waitForFunction(() => !!navigator.serviceWorker.controller, null, { timeout: 20_000 });
  return page;
}

test("the Service Worker activates, controls the page, and precaches the app shell", async () => {
  const ctx = await browser.newContext();
  try {
    const page = await loadControlled(ctx, `${server.baseURL}/`);
    const r = await page.evaluate(async () => {
      const names = await caches.keys();
      const staticName = names.find((n) => n.startsWith("static-"));
      const staticCache = staticName ? await caches.open(staticName) : null;
      const has = async (u: string) => (staticCache ? !!(await staticCache.match(u)) : false);
      return {
        controller: !!navigator.serviceWorker.controller,
        names,
        precached: { root: await has("/"), manifest: await has("/manifest.webmanifest"), wasm: await has("/assets/automerge.wasm") },
      };
    });
    // An active SW is in control of the page (network goes through its fetch handler).
    expect(r.controller, "navigator.serviceWorker.controller is non-null").toBe(true);
    // Caches are deploy-versioned (`static-<VERSION>`) — the key the activate reap keys on.
    expect(r.names.some((n) => /^static-\d/.test(n)), `a versioned static cache exists (${JSON.stringify(r.names)})`).toBe(true);
    // The app shell is precached at install: the three PRECACHE_URLS.
    expect(r.precached.root, "/ is precached").toBe(true);
    expect(r.precached.manifest, "/manifest.webmanifest is precached").toBe(true);
    expect(r.precached.wasm, "/assets/automerge.wasm is precached").toBe(true);
  } finally {
    await ctx.close();
  }
}, 120_000);

test("a previously-visited post still loads offline — network-first nav falls back to cache", async () => {
  const ctx = await browser.newContext();
  try {
    const page = await loadControlled(ctx, `${server.baseURL}/`);

    // Visit the post ONLINE first → the SW's network-first handler caches the
    // response into `runtime-<VERSION>`.
    await page.goto(`${server.baseURL}/posts/offer-files`, { waitUntil: "load", timeout: 30_000 });
    const onlineTitle = await page.title();
    expect(onlineTitle.length, "the post loads online with a title").toBeGreaterThan(0);

    // Cut the network, then re-navigate to the SAME post. With no network, a
    // network-first nav can only resolve if the SW serves the cached copy.
    await ctx.setOffline(true);
    const resp = await page.goto(`${server.baseURL}/posts/offer-files`, { waitUntil: "load", timeout: 30_000 });
    expect(resp?.ok(), "the offline navigation resolves (served from the SW cache)").toBe(true);

    const offline = await page.evaluate(() => ({ title: document.title, bodyLen: document.body.innerText.length }));
    expect(offline.title, "the cached post renders its real title while offline").toBe(onlineTitle);
    expect(offline.bodyLen, "the cached post renders its full article body offline").toBeGreaterThan(1000);

    await ctx.setOffline(false);
  } finally {
    await ctx.close();
  }
}, 120_000);

// Cross-deploy cache reap (proposal 22 §1, contract 3). Each deploy stamps the
// SW with a fresh `VERSION` (`Date.now()` at build/copy time), so the caches are
// keyed `static-<VERSION>` / `runtime-<VERSION>`; `activate` deletes every cache
// not ending in the *current* `-<VERSION>` and `clients.claim()`s. That's what
// keeps a returning reader from accumulating a stale deploy's bytes forever.
//
// We simulate a redeploy the way one actually reaches the browser: overwrite the
// served `dist/sw.js` with a bumped `VERSION` (wrangler serves it fresh — `/sw.js`
// is `Cache-Control: no-cache`), then `registration.update()`. The byte-different
// script installs, `skipWaiting()` activates it immediately, and its `activate`
// reap runs for real. Kept last in the file because it mutates the served script;
// `dist/sw.js` is snapshotted in beforeAll and restored in afterAll.
test("a redeploy (fresh VERSION) reaps the previous deploy's caches", async () => {
  const ctx = await browser.newContext();
  try {
    const page = await loadControlled(ctx, `${server.baseURL}/`);
    // Visit a post so the OLD deploy owns both a static- and a runtime- cache.
    await page.goto(`${server.baseURL}/posts/offer-files`, { waitUntil: "load", timeout: 30_000 });

    const v1 = (swOriginal.match(/const VERSION = "([^"]*)"/) || [])[1] ?? "";
    expect(v1, "the built sw.js carries a VERSION").toMatch(/^\d+$/);
    const before = await page.evaluate(() => caches.keys());
    expect(before, "the old deploy owns static- + runtime- caches").toEqual(
      expect.arrayContaining([`static-${v1}`, `runtime-${v1}`]),
    );

    // Redeploy: bump VERSION in the served sw.js (a later deploy timestamp).
    const v2 = String(Number(v1) + 1);
    writeFileSync(swPath, swOriginal.replace(/const VERSION = "[^"]*"/, `const VERSION = "${v2}"`));
    const served = await page.evaluate(async (base) => {
      const r = await fetch(base + "/sw.js", { cache: "no-store" });
      return r.text();
    }, server.baseURL);
    expect(served, "wrangler serves the bumped sw.js (no-cache)").toContain(`const VERSION = "${v2}"`);

    // The new SW installs (skipWaiting) and its activate reaps the old caches.
    await page.evaluate(async () => {
      const reg = await navigator.serviceWorker.getRegistration();
      await reg?.update();
    });
    let after: string[] = [];
    for (let i = 0; i < 40; i++) {
      await page.waitForTimeout(500);
      after = await page.evaluate(() => caches.keys());
      // Done once the new deploy's static cache exists and NO old-version cache remains.
      if (after.includes(`static-${v2}`) && !after.some((k) => k.endsWith(`-${v1}`))) break;
    }

    // The new deploy's app shell is precached…
    expect(after, "the new deploy precaches its static app shell").toContain(`static-${v2}`);
    // …and every cache from the previous deploy is gone (the reap).
    expect(
      after.filter((k) => k.endsWith(`-${v1}`)),
      `no previous-deploy caches survive (after=${JSON.stringify(after)})`,
    ).toEqual([]);
  } finally {
    writeFileSync(swPath, swOriginal); // restore immediately so later runs/fetches see the original
    await ctx.close();
  }
}, 120_000);
